### ISSUE TITLE
Would m64 borad update kernel to 4.14??

### ISSUE THREAD

**Issue by JimmyChangJY** [avafinger/bpi-m64-firmware#12]
Hello Avafinger 

I saw the news Linux Kernel 4.14 will support M64 board.

Would this project update to kernel 4.14??

I need some functions on 4.X kernel. For example BBR.

**Comment by avafinger** [comment]
Possible, Kernel 4.1x is missing CSI (camera) and some others things for a Desktop usage. Maybe if AW release new kernel (i think is 4.4) this could change in a near future. Let's wait for the next AW move, until there don't expect much improvement.

**Comment by JimmyChangJY** [comment]
So disapoint that Kernel 4.4 didn't support TCP BBR. (It need linux kernel 4.9+)  
One more thing. Why Armbian support Banana Pi( same AW A64 CPU) but no support Bananapi M64?
I have to complain.
Banana pi M64 like Orphan. Resource is very shortage.
Pine A64 got same AW A64 CPU. But I saw that Pine A64 Mainline kernel  is still ongoing. 
How about Banana PI M64??

I have to say I buy this Bananapi M64 board because you and this doop firmware. 
Stable, fast and can boot from emmc.
Thanks again, avafinger.

**Comment by avafinger** [comment]
Armbian works on modern kernel 4.13 but is a WiP and still in early stage.
As for the Pìne64, there are more kernel developers involved and the board came earlier, so more info.
Things will change soon with 4.14, there is already limited support for M64 (4.1x). To take advantage of the M64 features old kernel is needed, but don't worry M64 development is not stalled.

**Comment by avafinger** [comment]
Closing, there are now Kernel 4.19 from Armbian and 5.2 ofor testing here: https://github.com/avafinger/bananapi-m64-kodi

**Comment by JimmyChangJY** [comment]
GOOD JOB!! 
Thnaks avafinger
