### ISSUE TITLE
USB OTG broken

### ISSUE THREAD

**Issue by jvictorsoto** [avafinger/bpi-m64-firmware#13]
Seems that USB OTG is not working in last version, It works on last installed version I have on a few boards (before kernel update).

No +5V present when jumping OTG pins, it works fine with oficial distro.

**Comment by avafinger** [comment]
OTG has been disable to save CPU, please refer to this: https://github.com/avafinger/bpi-m64-firmware/issues/6 and use DTC to restore OTG usage. 
I've never used OTG and I thought nobody would use it, unless Android was used.

**Comment by jvictorsoto** [comment]
Hi, thanks for the quick reply.

I have enabled it, but indeed is causing high load on idle. Looking at http://www.cubieforums.com/index.php?topic=1084.0 they talk about a misconfiguration in the pins. Do you know if its the same cause here? 

I use OTG port to have an extra USB port without needing a hub, will be really bad losing it. Maybe is possible to configure it as a regular usb and disable OTG functionality ?

**Comment by avafinger** [comment]
usb_port_type: usb mode. 0-device, 1-host, 2-otg.

Change it to : 1
usb_port_type = <0x1>;

**Comment by jvictorsoto** [comment]
@avafinger Worked like a charm, looks like changing the type avoid the mode pooling which is the cause of the high load.

Great work by the way, I'm using this firmware in a few network probes and is the only firmware that can handle the gigabit traffic.
