### ISSUE TITLE
use update_wifi_bt.sh on old chip :(

### ISSUE THREAD

**Issue by Kang-Jack** [avafinger/bpi-m64-firmware#14]
what should i do if i used  update_wifi_bt.sh on  A64 chip accidentally ? :(

**Comment by avafinger** [comment]
Edit the two files:
```
sudo leafpad  /usr/local/bin/bpi-bt-patch
sudo leafpad  /usr/local/bin/bpi-bt-on
sync
```
and change bcm43438a1 to bcm43438a0, reboot and check wifi.

**Comment by Kang-Jack** [comment]
looks like these two files will change the Bluetooth,  and when i changed them to bcm43438a0  the Bluetooth devices manager disabled  all the functions , such as search ,pair, trust etc,,,
and i changed back to bcm43438a1, it can search the  device ,however when i tried to pair the device it  crashed internally  some error message like this  be print out  on console

 *** Error in `/usr/bin/python3': free(): invalid next size (fast): 0x000000000142f5f0 ***
*** Error in `/usr/bin/python3': free(): invalid next size (fast): 0x0000000001150400 ***

**Comment by Kang-Jack** [comment]
btw , i startup with SD card ( which not run update_wifi_bt.sh ), the  same error happened  when i try to pair the Bluetooth device

**Comment by avafinger** [comment]
Please, get a new sd card (brand new) and start all over again with this new card. Looks like you have a fake sd card. And make sure you power the board with a good 5v and 2.5A.

**Comment by Kang-Jack** [comment]
got it, thanks
