### ISSUE TITLE
How to enable 480p

### ISSUE THREAD

**Issue by azrin1972** [avafinger/bpi-m64-firmware#16]
Hi, I have a 480p display. How do I do this?

**Comment by avafinger** [comment]
Do this:

* Make a copy of the files you are about to change
* Decompile the current DTB (Device Tree Binary) in use so it can be changed
In shell type:
**cd /boot/m64** or **a64** and check with **ll**  and check where **m64.dtb** points to
decompile DTB to DTS with the command:
`sudo dtc -I dtb -O dts -o m64.dts m64.dtb`

PS: Please edit the file where m64.dtb points to and not the symlink

* Edit the file you just decompiled and change the section below:
screen0_output_mode = <**0x00000002**>;

**leafpad** your_file.dts
```

disp@01000000 {
            compatible = "allwinner,sun50i-disp";
            reg = <0x00000000 0x01000000 0x00000000 0x00300000 0x00000000 0x01c0c000 0x00000000 0x000017fc 0x00000000 0x01ca0000 0x00000000 0x000010fc>;
            interrupts = <0x00000000 0x00000056 0x00000104 0x00000000 0x00000057 0x00000104 0x00000000 0x00000059 0x00000104>;
            clocks = <0x0000006a 0x0000006b 0x0000006c 0x0000006d 0x0000006e>;
            status = "okay";
            device_type = "disp";
            disp_init_enable = <0x00000001>;
            disp_mode = <0x00000000>;
            screen0_output_type = <0x00000003>;
            screen0_output_mode = <0x00000002>;
            screen1_output_type = <0x00000003>;
            screen1_output_mode = <0x0000000a>;
            fb0_format = <0x00000000>;
            fb0_width = <0x00000000>;
            fb0_height = <0x00000000>;
            fb1_format = <0x00000000>;
            fb1_width = <0x00000000>;
            fb1_height = <0x00000000>;
        };

```

* Save and Recompile it to DTB again
`sudo dtc -I dts -O dtb -o destination_file.dtb source_file.dts`

* sync && reboot


**Available hdmi modes**
screenx_output_mode   (used for hdmi output, 0:480i 1:576i 2:480p 3:576p 4:720p50)
                                     (5:720p60 6:1080i50 7:1080i60 8:1080p24 9:1080p50 10:1080p60)

**Comment by azrin1972** [comment]
Thank you 

Will try it out and will let you know the out come. 

Sincerely 
Azrin

**Comment by azrin1972** [comment]
Ok I did the test last week - the display works but after a few minutes, I got gibberish display. Seems like the OS is trying to change the HDMI resolution.

How do I fixed this to 480p only?

**Comment by avafinger** [comment]
Did you enable sleep mode for the monitor or turned the monitor off or something ?

**Comment by azrin1972** [comment]
I’ve not set anything. The display is a bare display without casing. It has only HDMI port. 

Sincerely 
Azrin

**Comment by avafinger** [comment]
I mean "standby mode" or it happens while you are working / typing / moving the mouse?

**Comment by azrin1972** [comment]
I’m using it for a system display. No user interaction

Sincerely 
Azrin

**Comment by azrin1972** [comment]
I’ve used a 720 display and I got no issue of it. It’s just that the 720 is big and won’t fit the housing

Sincerely 
Azrin

**Comment by avafinger** [comment]
Hmm ok. 
You can try to edit **uEnv.txt** and add text to the ine:
console=tty0 console=ttyS0,115200n8 **no_console_suspend consoleblank=0**

If you are using kernel 3.10 you could try out the 4.4 and see if you get better results? I doubt it due to cec in 4.4.

Hope you are using HDMI to HDMI and not anything between.

**Comment by azrin1972** [comment]
Thanks, 

I will try it out. 

And yes, it’s a straight HDMI-HDMI connection 

Sincerely 
Azrin
