### ISSUE TITLE
LED does not light up

### ISSUE THREAD

**Issue by kometchtech** [avafinger/bpi-m64-firmware#4]
Hello,

I updated kernel to 3.10.105, but I tried to turn on the LED in the procedure in the readme, but it does not light up.

In this case, do I need to redo the Kernel update procedure?

It seems that it is loaded in dmesg ...

```
[    8.465164] gpio_led_probe start
[    8.465185] led1 gpio number is 143
[    8.465188] led1_trigger led trigger name is heartbeat
[    8.465193] led2 gpio number is 142
[    8.465195] led2_trigger led trigger name is mmc0
```

Thanks.

**Comment by avafinger** [comment]
If you load the camera, the LEDs stops working.
Please, comment (#) the v4l2 and camera on /etc/modules and boot again.

**Comment by kometchtech** [comment]
Thank you for your quick answer.

As you said, the LED will light up when you specify blacklist.

```
kometch@dns03:/etc/modprobe.d$ cat bpi-blacklist.conf
blacklist vfe_v4l2

```
