### ISSUE TITLE
AUDIO Won't work

### ISSUE THREAD

**Issue by JimmyChangJY** [avafinger/bpi-m64-firmware#7]
I try everything. 
a64-2GB.dtb_                  analog_sound_output
a64-2GB_codec.dtb	        Fix for codec	
a64-2GB_codec2.dtb	another attempt to fix audiocode
a64-2GB_codec3.dtb	fix: dvfs tabl
none of these work....
It is not silent at all. The HDMI TV speaker did has some "noise" come out.
But none of these a64 files let the microphone work. 
Not to mention analog audio speaker. 
Any log file I need to print here?

**Comment by avafinger** [comment]
Which kernel you are running? Can you update to the latest kernel?
Latest:
https://github.com/avafinger/bpi-m64-firmware/commit/4d7ddeb40ff418cf69f887d070c8e9c9a20433b4

Try this:
[a64-2GB_720p_1080p.zip](https://github.com/avafinger/bpi-m64-firmware/files/1272316/a64-2GB_720p_1080p.zip)

**a) Use one of these DTB (attached),  720p and/or 1080p.**

**b) Update alsa sane values**
```
wget https://raw.githubusercontent.com/longsleep/build-pine64-image/master/blobs/asound.state
sudo mkdir -p /var/lib/alsa
sudo mv asound.state /var/lib/alsa/asound.state
```

**c) UnMute all you need with alsamixer**
`sudo alsamixer`

**d) reboot**

PS:
* if you have trouble, remove alsa-tools and start with HDMI sound first.

later:
```
sudo apt-get install alsa-base alsa-utils
sudo apt-get install pulseaudio

```

**Comment by JimmyChangJY** [comment]
I kernel is latest one. 3.10.105.
Because the BLUE LED !! Haha ...
```
uname -r
3.10.105
```
1. I use a64-2GB_1080p.zip
2. I Update alsa sane values
3. I unMute all alsamixser
4 reboot 

When I change to analog out. I can see the volume bar up and down. 
But if I change to HDMI. The volume bar won't change. 
None of one come out any "noise". (Even if noise.....) 

PS: I change two speakers. One is connecting with my Amazon Echo Dot now. 
So the Speaker is no problem. 

http://i63.tinypic.com/25taqzo.png
<a href="http://tinypic.com?ref=2gx4uq8" target="_blank"><img src="http://i63.tinypic.com/2gx4uq8.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by avafinger** [comment]
I have not played with Firefox sound or video since there is no HW video acceleration  support for it.
Please, test with mplayer to see if you have sound output to HDMI and/or JACK, so we make sure sound is coming out.

**Download some MP4 video (H264) and do:**

* use your MP4, in the sample below i used big_buck_bunny_1080p_H264_AAC_25fps_7200K.MP4 
* Sound output to HDMI
`mplayer-hdmi big_buck_bunny_1080p_H264_AAC_25fps_7200K.MP4 `
* Sound output to JACK
`mplayer-jack big_buck_bunny_1080p_H264_AAC_25fps_7200K.MP4 `

If you see some delay/stutter with video and sound, you should remove alsa-tools and alsa-utils, remove all sunxi_codec from modules, and start over again, first with HDMI output only, then with JACK.

With jack you should load in /etc/modules
```
sunxi_codec
sunxi_i2s
sunxi_sndcodec
```

Once you get this working you should move on to configuring **Firefox**

**Comment by JimmyChangJY** [comment]
Thanks  avafinger.

I download some mp4 files from this website
http://www.sample-videos.com/index.php#sample-mp4-video

VLC player
HDMI work with  
ALSA audio output 
sndhdmi:Direct sample mixing device 
Only this condition can work. If I choose other device will cause movie lag or player crash.

And I try mplayer also. 
Same situation. Only one condition when you choose sndhdmi(alsa) can work smooth.


But none of one can let the AUDIO JACK work.
No matter I choose any device. 

/etc/modules load in 
```
sunxi_codec
sunxi_i2s
sunxi_sndcodec
```

**Comment by avafinger** [comment]
Can you please try with this dtb?
Check if you have errors in your **dmesg**

```
sudo dmesg|grep erro
sudo dmesg|grep fail
sudo dmesg|grep TRACE
```
[a64-2GB.dtb_1080p.zip](https://github.com/avafinger/bpi-m64-firmware/files/1274933/a64-2GB.dtb_1080p.zip)

**Comment by JimmyChangJY** [comment]
sudo dmesg|grep error
```
ubuntu@Jimmy-M64:~$ dmesg|grep error
[   18.568430] sunxi-ohci: probe of 1c1a000.ohci0-controller failed with error -1
[   18.639805] sunxi-ohci: probe of 1c1b000.ohci1-controller failed with error -1
[   24.484678] [VFE_ERR]vfe sensor register check error at input_num = 0
[  317.081553] EXT4-fs (mmcblk0p2): error count since last fsck: 3
[  317.081577] EXT4-fs (mmcblk0p2): initial error at time 1455208082: ext4_mb_generate_buddy:755
[  317.081593] EXT4-fs (mmcblk0p2): last error at time 1455208082: ext4_mb_generate_buddy:755

```
sudo dmesg|grep fail
```
ubuntu@Jimmy-M64:~$ dmesg|grep fail
[   16.941162] add_sys_pwr_dm: get ldo name  for id: vcc-lpddr failed
[   17.013223] [DISP] disp_boot_para_parse,line:301:of_property_read disp.boot_disp fail
[   17.013842] [DISP] disp_sys_script_get_item,line:193:of_find_compatible_node allwinner,sunxi-lcd1 fail
[   17.014005] [DISP] disp_sys_script_get_item,line:193:of_find_compatible_node allwinner,sunxi-lcd1 fail
[   17.014165] [DISP] disp_sys_script_get_item,line:193:of_find_compatible_node allwinner,sunxi-lcd1 fail
[   17.015483] [DISP] disp_boot_para_parse,line:301:of_property_read disp.fb_base fail
[   18.211996] WARNING: Get ephy clock is failed
[   18.343824] get ehci1-controller drv_vbus_gpio is fail
[   18.538844] hci: ERR: ohci0-controller get usb clk_usbohci12m clk failed.
[   18.553703] sunxi-ohci 1c1a000.ohci0-controller: init_sunxi_hci is fail
[   18.568430] sunxi-ohci: probe of 1c1a000.ohci0-controller failed with error -1
[   18.583875] get ohci1-controller drv_vbus_gpio is fail
[   18.610449] hci: ERR: ohci1-controller get usb clk_usbohci12m clk failed.
[   18.625233] sunxi-ohci 1c1b000.ohci1-controller: init_sunxi_hci is fail
[   18.639805] sunxi-ohci: probe of 1c1b000.ohci1-controller failed with error -1
[   20.279962] [DISP] disp_boot_para_parse,line:301:of_property_read disp.boot_disp fail
[   20.605894] thermal thermal_zone0: failed to read out thermal zone 0
[   22.216193] systemd[1]: keyboard-setup.service: Unit entered failed state.
[   24.214766] [VFE_WARN]fetch csi0_dev0_twi_id from device_tree failed
[   24.231404] [VFE_WARN]fetch csi0_dev0_afvdd from device_tree failed
[   24.248037] [VFE_WARN]fetch csi0_dev0_afvdd_vol from device_tree failed
[   24.262912] [VFE_WARN]fetch csi0_dev0_power_en from device_tree failed
[   24.309300] [VFE_WARN]fetch csi0_dev0_flash_en from device_tree failed
[   24.326158] [VFE_WARN]fetch csi0_dev0_flash_mode from device_tree failed
[   24.341459] [VFE_WARN]fetch csi0_dev0_af_pwdn from device_tree failed

```
no meesage  for sudo dmesg|grep TRACE

**Comment by avafinger** [comment]
Ok, i will revisit ALSA and see if i get it right. I am experimenting with new u-boot and kernel with different DT, it may take some time.

Nothing to do with Audio JACK issue but you should run a fsck on you eMMC or/and SD CARD.

* umount the eMMC (boot from an SD CARD)
* run the fsck


**sd card** (in a HOST PC)

```
sudo umount /media/sdX
sync
sudo fsck.vfat -a /dev/sdX1
sync
sudo fsck.ext4 -f /dev/sdX2 (Fix ERRORS manually, answer YES)

```

**for the eMMC (boot from SD CARD)**

check which dev is the eMMC with:
`df -lh`

uMout the emmc:
```
sudo umount /media/ubuntu/emmcboot
sudo umount /media/ubuntu/emmcrootfs
sync
sudo fsck.vfat -a /dev/mmcblk? (where ? is your eMMC device number from df -lh)
sync
sudo fsck.ext4 -f /dev/mmcblk? (Fix ERRORS manually, answer YES)
```

**Comment by avafinger** [comment]
ok, testing with new kernel shows hdmi sound output and jack output works. will push to github asap.

**Comment by avafinger** [comment]
Please, try with this new kernel and new hw config. It works for me.

**Comment by JimmyChangJY** [comment]
Thanks avafinger!! 👍 
Kindly remind. Don't forget the MICROPHONE!!
I want to build Amazon Alexa system on M64 ✌️

**Comment by JimmyChangJY** [comment]
How can I update the kernel and HW config??
 
Step 1
```
git clone https://github.com/avafinger/bpi-m64-firmware
cat rootfs_m64_a64_rc1.tar.gz.* > rootfs_m64_a64_rc1.tar.gz
```

Step2 
```
tar -xvpzf rootfs_m64_a64_rc1.tar.gz -C ./erootfs --numeric-ow
sync
sudo umount erootfs
rm -fR erootfs
```
Step3
```
tar -xvzf boot_m64_a64_rc1.tar.gz -C ./eboot
sync
sudo umount eboot
rm -fR eboot
sync
```

Correct????

**Comment by avafinger** [comment]
Steps:

a) Flash a new SD CARD with latest kernel (the new u-boot has changed the order of the devices)
b) Boot it with this new SD CARD
c) Do your Step1 and Step2(use **sudo** in step2)

**Step3 (new u-boot):**
```
umount the boot partition:
sudo umount /dev/mmcblk1p1 (make sure boot partition from eMMC is umounted)


sudo dd if=./ub-m64-emmc.bin conv=notrunc bs=1k seek=8 of=/dev/mmcblk1
sudo mkfs.ext4 -F -b 4096 -E stride=2,stripe-width=1024 -L boot /dev/mmcblk1p1
sudo partprobe /dev/mmcblk1p1
mkdir eboot
sudo mount /dev/mmcblk1p1 eboot
sudo tar -xvzf boot_m64_a64_rc1.tar.gz -C ./eboot
sync
sudo umount eboot
rm -fR eboot
sync

**Comment by JimmyChangJY** [comment]
dd and partprobe the emmc ???
so I will lost my data? Is that nessery?
what is the step that I can keep my old data. And update the kernel only. 
Because I change so many stuff, for ex., Chinese system, Chinese input, Chinese font.... 

BTW. why I can use firefox only? I install the chromium. But it won't work.
Thanks again avafinger

**Comment by avafinger** [comment]
We are changing partition 1 to use **EXT4** (you have it as a **FAT32** now) and writing new u-boot in there, that is necessary. Update kernel only won't help.

The partition 2 where **rootfs** resides will not be touched.
For this to work you need to boot with **SD CARD** with the **new kernel and geometry** and only then do the **step3** .

You should not loose data, but you know, there is always a risk involved when it is not tested and Moore's law can hit hard. If something goes wrong with **partition 1** you will not be able to boot again but rootfs will be intact and a fix will be needed.

in **HOME** directory and **ROOT** directory there is a file **./bash_history** that stores all commands you typed, but if you install via Graphics (Desktop configuration) you need to redo all over again, sorry.
But is a great opportunity to document all steps, so you will master this and can perhaps publish it to help you and others.

**Comment by JimmyChangJY** [comment]
I try three days with new  kernel.
ALSA with speaker out still no work.

I load the all module. 
sunxi_codec
sunxi_i2s
sunxi_sndcodec

HDMI is good. I can play movie with VLC or gnone mplayer.
But the speaker out still no good.
No matter which device I choose.  

Any Idea?
HW issue?

**Comment by avafinger** [comment]
Did you unMute all and increase volume? 
Please refer to: https://wiki.ubuntu.com/Audio/Alsamixer

**sudo alsamixer**

Did you try with headphone? In my test the volume was very low on headphone.
I just think is configuration, not HW issue.
Maybe this can help a bit: http://alsa.opensrc.org/Speaker-test

**Comment by avafinger** [comment]
asound.conf is incorret, please, try with:

**/etc/asound.conf** 

pcm.!default {
  type hw
  card 1
  device 0
}
ctl.!default {
  type hw
  card 1
}

refer to: http://linux-sunxi.org/Audio_Codec

**Comment by avafinger** [comment]
FYI, in my configuration for the JACK sound output i can hear the right channel only.
I used mplayer-jack to test sound output, check if this works for you.

**Comment by JimmyChangJY** [comment]
I check everything. Over and over again. 
I check asound.state in the /var/lib/alsa.
I install alsa-base alsa-utils  pulseaudio
I unmute everything in the alsamixer.


I run mplayer-hdmi 
Good

Then I run mplayer-jack 
Still NG, only video no audio.

I try three different speakers and earphone. 

message at below 

```
MPlayer 1.2.1 (Debian), built with gcc-5.3.1 (C) 2000-2016 MPlayer Team
mplayer: could not connect to socket
mplayer: No such file or directory
Failed to open LIRC support. You will not be able to use your remote control.

Playing /home/ubuntu/Downloads/SampleVideo_1280x720_5mb.mp4.
libavformat version 56.40.101 (external)
libavformat file format detected.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fa0db3608]Protocol name not provided, cannot determine if input is local or a network protocol, buffers and access patterns cannot be configured optimally without knowing the protocol
[lavf] stream 0: video (h264), -vid 0
[lavf] stream 1: audio (aac), -aid 0, -alang und
VIDEO:  [H264]  1280x720  24bpp  25.000 fps  1033.0 kbps (126.1 kbyte/s)
Clip info:
 major_brand: isom
 minor_version: 512
 compatible_brands: isomiso2avc1mp41
 creation_time: 1970-01-01 00:00:00
 encoder: Lavf53.24.2
Load subtitles in /home/ubuntu/Downloads/
[VDPAU SUNXI] VE version 0x1689 opened
[VDPAU SUNXI] OSD disabled!
==========================================================================
Forced video codec: ffmpeg12vdpau
Forced video codec: ffh264vdpau
Opening video decoder: [ffmpeg] FFmpeg's libavcodec codec family
libavcodec version 56.60.100 (external)
Selected video codec: [ffh264vdpau] vfm: ffmpeg (FFmpeg H.264 (VDPAU))
==========================================================================
==========================================================================
Opening audio decoder: [ffmpeg] FFmpeg/libavcodec audio decoders
AUDIO: 48000 Hz, 6 ch, floatle, 384.0 kbit/4.17% (ratio: 47995->1152000)
Selected audio codec: [ffaac] afm: ffmpeg (FFmpeg AAC (MPEG-2/MPEG-4 Audio))
==========================================================================
[AO_ALSA] Format floatle is not supported by hardware, trying default.
AO: [alsa] 48000Hz 2ch s16le (2 bytes per sample)
Starting playback...
Movie-Aspect is 1.78:1 - prescaling to correct movie aspect.
VO: [vdpau] 1280x720 => 1280x720 H.264 VDPAU acceleration 
Movie-Aspect is 1.78:1 - prescaling to correct movie aspect.
VO: [vdpau] 1280x720 => 1280x720 H.264 VDPAU acceleration 
A:   7.6 V:   7.6 A-V: -0.003 ct:  0.048   0/  0 18% 24%  6.9% 12 0 

Exiting... (Quit)
```

Then I check 
`dmesg|grep fail
alloc_contig_range test_pages_isolated(bc486, bc5e4) failed
`
I saw over 30 lines error message. 

So I google it. 

I find you had same issue. 

https://github.com/linux-sunxi/libvdpau-sunxi/issues/56

Any idea????

:taiwan: :taiwan: :taiwan: :+1:

**Comment by JimmyChangJY** [comment]
ubuntu@Jimmy:/tmp$ aplay -l
```

**** List of PLAYBACK Hardware Devices ****
card 0: audiocodec [audiocodec], device 0: SUNXI-CODEC codec-aif1-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: audiocodec [audiocodec], device 1: bb Voice codec-aif2-1 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: audiocodec [audiocodec], device 2: bb-bt-clk codec-aif2-2 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: audiocodec [audiocodec], device 3: bt Voice codec-aif3-3 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: sndhdmi [sndhdmi], device 0: SUNXI-HDMIAUDIO sndhdmi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

```

**Comment by JimmyChangJY** [comment]
What is ALSA lib pcm.c error message??
(snd_pcm_open_noupdate) Unknown PCM audiocodec
```


ubuntu@Jimmy:~$ speaker-test --device audiocodec

speaker-test 1.1.0

Playback device is audiocodec
Stream parameters are 48000Hz, S16_LE, 1 channels
Using 16 octaves of pink noise
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM audiocodec
Playback open error: -2,No such file or directory

```

**Comment by avafinger** [comment]
You should test like so:

speaker-test -Dplughw:0 -t wav -c4 (audiocodec)
speaker-test -Dplughw:1 -t wav -c4 (hdmi)

aplay Miami_Twice.wav -Dplughw:1 (hdmi)
aplay Miami_Twice.wav -Dplughw:0 (audicodec)


Currently working JACK sound output (right channel only, don't know why yet) for your reference and looks very similar to your output:

```
ubuntu@bpi-m64:~/mp4$ mplayer-jack drift.mp4 
MPlayer 1.2.1 (Debian), built with gcc-5.3.1 (C) 2000-2016 MPlayer Team
mplayer: could not connect to socket
mplayer: No such file or directory
Failed to open LIRC support. You will not be able to use your remote control.

Playing drift.mp4.
libavformat version 56.40.101 (external)
libavformat file format detected.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f82f33608]Protocol name not provided, cannot determine if input is local or a network protocol, buffers and access patterns cannot be configured optimally without knowing the protocol
[lavf] stream 0: video (h264), -vid 0
[lavf] stream 1: audio (aac), -aid 0, -alang und
VIDEO:  [H264]  1280x720  24bpp  23.976 fps  2710.7 kbps (330.9 kbyte/s)
Clip info:
 major_brand: mp42
 minor_version: 0
 compatible_brands: isommp42
 creation_time: 2013-11-12 05:10:37
Load subtitles in ./
[VDPAU SUNXI] VE version 0x1689 opened
[VDPAU SUNXI] OSD disabled!
==========================================================================
Forced video codec: ffmpeg12vdpau
Forced video codec: ffh264vdpau
Opening video decoder: [ffmpeg] FFmpeg's libavcodec codec family
libavcodec version 56.60.100 (external)
Selected video codec: [ffh264vdpau] vfm: ffmpeg (FFmpeg H.264 (VDPAU))
==========================================================================
==========================================================================
Opening audio decoder: [ffmpeg] FFmpeg/libavcodec audio decoders
AUDIO: 44100 Hz, 2 ch, floatle, 192.0 kbit/6.80% (ratio: 24000->352800)
Selected audio codec: [ffaac] afm: ffmpeg (FFmpeg AAC (MPEG-2/MPEG-4 Audio))
==========================================================================
[AO_ALSA] Format floatle is not supported by hardware, trying default.
AO: [alsa] 44100Hz 2ch s16le (2 bytes per sample)
Starting playback...
Movie-Aspect is undefined - no prescaling applied.
VO: [vdpau] 1280x720 => 1280x720 H.264 VDPAU acceleration 
Movie-Aspect is undefined - no prescaling applied.
VO: [vdpau] 1280x720 => 1280x720 H.264 VDPAU acceleration 
A:  49.5 V:  49.5 A-V: -0.000 ct:  0.047   0/  0 15% 13%  5.2% 2 0 

Exiting... (Quit)

```

**Comment by avafinger** [comment]
> Then I check
> dmesg|grep fail alloc_contig_range test_pages_isolated(bc486, bc5e4) failed
> I saw over 30 lines error message.
> 
> So I google it.
> 
> I find you had same issue.
> 
> linux-sunxi/libvdpau-sunxi#56
> 
> Any idea????

That was not the same issue, the video was kind of "stuttering", now you have perfect video without sound output.

But  **test_pages_isolated** could be related to the problem. I will play the same video and see if i get same errors.

I think there is a script called **m64_moniotr.sh** , run this and monitor the hardware while playing video and sound.

**Comment by avafinger** [comment]
Can you please flash a fresh SD CARD (just for test) and run the same video without changing anything and see if you get something coming out from JACK? Please try with headphones also, maybe there is something with the plug.

**Comment by JimmyChangJY** [comment]
Okay, I flash two different size SD cards with new kernel. 
I didn't change anything.  And I try 
`speaker-test -Dplughw:0 -t wav -c4`

And I try two speakers and two headphones. (Logitech and AKG) 
Nothing come out. 

BTW, HDMI audio is good.

**Comment by avafinger** [comment]
Please, check dmesg output if we can find any clue. I can't think of anything else to try.

dmesg|grep err
dmesg|grep sound
dmesg|grep fail

**Comment by JimmyChangJY** [comment]
Message from SD Card 

ubuntu@bpi-m64:~$ dmesg|grep sound
```
[   19.622904] sunxi-codec-machine sound.5:  codec-aif1 <-> 1c22c00.i2s0-controller mapping ok
[   19.636026] sunxi-codec-machine sound.5:  codec-aif2 <-> bb-dai mapping ok
[   19.636197] sunxi-codec-machine sound.5:  codec-aif2 <-> bb-dai mapping ok
[   19.636317] sunxi-codec-machine sound.5:  codec-aif3 <-> bb-dai mapping ok
[   19.637250] input: audiocodec sunxi Audio Jack as /devices/soc.0/sound.5/sound/card0/input3
[   19.705079] sndhdmi sound.6:  sndhdmi <-> 1c22800.daudio mapping ok
ubuntu@bpi-m64:~$  speaker-test -Dplughw:0 -t wav -c4
```
ubuntu@bpi-m64:~$ dmesg|grep err
```
[   16.376936] kvm [1]: interrupt-controller@1c84000 IRQ25
[   18.749203] sunxi-mmc 1c0f000.sdmmc: smc 0 p0 err, cmd 52, RTO !!
[   18.869927] sunxi-mmc 1c0f000.sdmmc: smc 0 p0 err, cmd 52, RTO !!
[   18.874457] sunxi-mmc 1c0f000.sdmmc: smc 0 p0 err, cmd 5, RTO !!
[   18.875266] sunxi-mmc 1c0f000.sdmmc: smc 0 p0 err, cmd 5, RTO !!
[   18.876075] sunxi-mmc 1c0f000.sdmmc: smc 0 p0 err, cmd 5, RTO !!
[   18.876884] sunxi-mmc 1c0f000.sdmmc: smc 0 p0 err, cmd 5, RTO !!
[   19.112117] sunxi-mmc 1c11000.sdmmc: smc 1 p2 err, cmd 52, RTO !!
[   19.122839] sunxi-mmc 1c11000.sdmmc: smc 1 p2 err, cmd 52, RTO !!
[   19.127074] sunxi-mmc 1c11000.sdmmc: smc 1 p2 err, cmd 8, RTO !!
[   19.127884] sunxi-mmc 1c11000.sdmmc: smc 1 p2 err, cmd 5, RTO !!
[   19.128693] sunxi-mmc 1c11000.sdmmc: smc 1 p2 err, cmd 5, RTO !!
[   19.129499] sunxi-mmc 1c11000.sdmmc: smc 1 p2 err, cmd 5, RTO !!
[   19.130309] sunxi-mmc 1c11000.sdmmc: smc 1 p2 err, cmd 5, RTO !!
[   19.131121] sunxi-mmc 1c11000.sdmmc: smc 1 p2 err, cmd 55, RTO !!
[   19.131930] sunxi-mmc 1c11000.sdmmc: smc 1 p2 err, cmd 55, RTO !!
[   19.132740] sunxi-mmc 1c11000.sdmmc: smc 1 p2 err, cmd 55, RTO !!
[   19.133549] sunxi-mmc 1c11000.sdmmc: smc 1 p2 err, cmd 55, RTO !!
[   19.773436] sunxi-mmc 1c10000.sdmmc: smc 2 p1 err, cmd 52, RTO !!
[   19.774245] sunxi-mmc 1c10000.sdmmc: smc 2 p1 err, cmd 52, RTO !!
[   19.778479] sunxi-mmc 1c10000.sdmmc: smc 2 p1 err, cmd 8, RTO !!
[   19.779286] sunxi-mmc 1c10000.sdmmc: smc 2 p1 err, cmd 5, RTO !!
[   19.780090] sunxi-mmc 1c10000.sdmmc: smc 2 p1 err, cmd 5, RTO !!
[   19.780895] sunxi-mmc 1c10000.sdmmc: smc 2 p1 err, cmd 5, RTO !!
[   19.781699] sunxi-mmc 1c10000.sdmmc: smc 2 p1 err, cmd 5, RTO !!
[   19.782509] sunxi-mmc 1c10000.sdmmc: smc 2 p1 err, cmd 55, RTO !!
[   19.783316] sunxi-mmc 1c10000.sdmmc: smc 2 p1 err, cmd 55, RTO !!
[   19.784123] sunxi-mmc 1c10000.sdmmc: smc 2 p1 err, cmd 55, RTO !!
[   19.784930] sunxi-mmc 1c10000.sdmmc: smc 2 p1 err, cmd 55, RTO !!
[   19.785777] sunxi-mmc 1c10000.sdmmc: smc 2 p1 err, cmd 1, RTO !!
[   21.790401] sunxi-mmc 1c10000.sdmmc: smc 2 p1 err, cmd 52, RTO !!
[   21.791208] sunxi-mmc 1c10000.sdmmc: smc 2 p1 err, cmd 52, RTO !!
[   21.795405] sunxi-mmc 1c10000.sdmmc: smc 2 p1 err, cmd 8, RTO !!
[   21.951267] dhd_deferred_work_init: work queue initialized 
[   21.959307] dhd_module_init: Exit err=0
```
ubuntu@bpi-m64:~$ dmesg|grep fail
```
[   16.307393] add_sys_pwr_dm: get ldo name  for id: vcc-lpddr failed
[   16.384826] [DISP] disp_boot_para_parse,line:301:of_property_read disp.boot_disp fail
[   16.385439] [DISP] disp_sys_script_get_item,line:193:of_find_compatible_node allwinner,sunxi-lcd1 fail
[   16.385598] [DISP] disp_sys_script_get_item,line:193:of_find_compatible_node allwinner,sunxi-lcd1 fail
[   16.385754] [DISP] disp_sys_script_get_item,line:193:of_find_compatible_node allwinner,sunxi-lcd1 fail
[   16.387148] [DISP] disp_boot_para_parse,line:301:of_property_read disp.fb_base fail
[   16.417713] [DISP] disp_boot_para_parse,line:301:of_property_read disp.boot_disp fail
[   17.762551] WARNING: Get ephy clock is failed
[   17.802724] sunxi-ehci 1c1a000.ehci0-controller: init_sunxi_hci is fail
[   17.814094] get ehci1-controller drv_vbus_gpio is fail
[   17.978566] sunxi-ohci 1c1a000.ohci0-controller: init_sunxi_hci is fail
[   17.989883] get ohci1-controller drv_vbus_gpio is fail
[   20.024347] thermal thermal_zone0: failed to read out thermal zone 0

```

**Comment by avafinger** [comment]
Nothing wrong!

I can only suggest to review alsamixer configurations. Also check pcm configuration.

**Comment by avafinger** [comment]
Please, refer to the video about Jack sound output: https://youtu.be/4PtbJckmFA8
Needs a way to increase volume on alsamixer...

**Comment by JimmyChangJY** [comment]
I almost can make sure this is H/W issue. 
When I use below command to test
`speaker-test -Dplughw:0 -t wav -c4
`
I can hear very very very tiny noise from the speaker. 
left speak one time and right speak one time. 
That fit the test sound. 
I may buy another one M64 to verify this issue. 

Again the HDMI is good. So I will move on the FIREFOX and CHROME web sound issue. 

Thanks avafinger.

**Comment by avafinger** [comment]
How did you fix?

**Comment by kirantpatil** [comment]
Hi,

We faced same issue and we could hear with only 10% of clarity.

From alsamixer we enabled all options, then only we started to hear some voice.

We are looking for out of the box Microphone and Speaker to work properly.

From the [forum](http://forum.banana-pi.org/t/banan-pi-bpi-m64-for-linux-kernel-4-4-development/5335/4) someone ported Kernel 4.4 to M64 but it is still not available for testing.

Does Kernel 4.4 resolve this issue ?

When can we expect the updated 4.4 BSP ?

Regards,
Kiran.

**Comment by avafinger** [comment]
I have Kernel 4.4.y running on M64 but still facing some issues:

* Gigabit Ethernet with high latency and then stop working after 10 minutes or so, unusable..
* sndcodec setup seems to conflict with Gbit ,  i was able to work around this issue but have not tested Microphone and Speaker yet. I can't say it works properly.

My M64 belongs to the first batch that was made, you possibly need to update Wifi firmware if you want wlan0 to work properly. It works for my HW revision.

I can push an Image so you can check out the state of sndcodec and workout with alsamixer and tell the results.

**Comment by avafinger** [comment]
@kirantpatil 
There is a new experimental image with kernel 4.4 you can test and check if sndcodec is working as you expected, you need to configure it from scratch, please share your results.

Image is at: https://mega.nz/#F!wXwlRRZR!0BCmUo2F2hg7rG4Ax69bkw
