### ISSUE TITLE
ADSL PPPOE missing ppp_generic

### ISSUE THREAD

**Issue by JimmyChangJY** [avafinger/bpi-m64-firmware#9]
Is me again.
I run the ppoeconf

error message will show below  
```
Couldn't open the /dev/ppp device: No such device or address
modprobe: FATAL: Module ppp_generic not found in directory /lib/modules/3.10.105-a64
/usr/sbin/pppd: Please load the ppp_generic kernel module.

```
So I change the  /lib/modules/3.10.105-a64/modules.alias 
from
`alias char-major-99-* ppdev
`
to 
`alias char-major-99-* ppp_generic
`
Nothing change..

What/Where need to modify the configuration?
Thanks.

**Comment by avafinger** [comment]
Sorry, PPP network is not enabled in this kernel. Will see if i can enable it.

**Comment by avafinger** [comment]
@JimmyChangJY ,

I have a new kernel with PPP/PPOe support, can you test with this kernel? I will provide instructions to update kernel,

**Comment by avafinger** [comment]
Please, update with this instructions: https://github.com/avafinger/bpi-m64-firmware#kernel-update-for-ppp--pppoe

PS: updating fstab will brake the script to change the screen resolution but it can be fixed later.

**Comment by JimmyChangJY** [comment]
I can get the ppp0 ip 
But seems the iptable and route table has some problem.
I can only ping 192.168.1.1 (my ADSL router IP)  and my ppp0 IP address.
That is all. 
I can't ping any other IP address. 
When I type iptable -L 
There is no any ip table build.

Even I unplug the ethernet and back to the Wi-Fi 
I need to ifdown eth0 again to release the eth0 ip.
Then I can connect the internet via the Wi-Fi 

```

ifconfig
eth0      Link encap:Ethernet  HWaddr 36:c9:e3:f1:b8:05  
          inet addr:192.168.1.2  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::34c9:e3ff:fef1:b805/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:249 errors:0 dropped:0 overruns:0 frame:0
          TX packets:218 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:24716 (24.7 KB)  TX bytes:17081 (17.0 KB)
          Interrupt:114 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:87 errors:0 dropped:0 overruns:0 frame:0
          TX packets:87 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:6963 (6.9 KB)  TX bytes:6963 (6.9 KB)

ppp0      Link encap:Point-to-Point Protocol  
          inet addr:100.64.248.232  P-t-P:100.64.0.1  Mask:255.255.255.255
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1492  Metric:1
          RX packets:4 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:3 
          RX bytes:68 (68.0 B)  TX bytes:54 (54.0 B)


```

**Comment by JimmyChangJY** [comment]
two gateways cause the problem. 
I CLOSE the eth0 dhcp. 
Everything is fine now.
